spring:
  cloud:
    gcp:
      project-id: apt-achievment-268700
      sql:
        instance-connection-name: apt-achievment-268700:us-central1:test
        database-name: test
        enabled: true
  datasource:
    username: test
    password: 123456
    initialization-mode: always
    url: jdbc:postgresql://google/test?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=apt-achievment-268700:us-central1:test&ssl=false


  jpa:
    hibernate:
      ddl-auto: update
